services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: tery
      MYSQL_PASSWORD: tery
    command: --init-file /docker-entrypoint-initdb.d/user.sql
    volumes:
      - ./data/db:/var/lib/mysql
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  zoo1:
    image: wurstmeister/zookeeper:latest
    hostname: zoo1
    container_name: zoo1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka1:
    image: wurstmeister/kafka:latest
    hostname: kafka1
    container_name: kafka1
    depends_on:
      zoo1:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: nc -z localhost 9092

  ms_analytics:
    build: ./ms_analytics
    ports:
      - "3006:3006"
    env_file:
      - ./ms_analytics/.env
    depends_on:
      kafka1:
        condition: service_healthy
      db:
        condition: service_healthy
    hostname: ms_analytics

  ms_choreographer:
    build: ./ms_choreographer
    ports:
      - "3001:3001"
    env_file:
      - ./ms_choreographer/.env  
    depends_on:
      kafka1:
        condition: service_healthy
      db:
        condition: service_healthy
    hostname: ms_choreographer

  ms_data_input:
    build: ./ms_data_input
    ports:
      - "3002:3002"
    env_file:
      - ./ms_data_input/.env
    depends_on:
      kafka1:
        condition: service_healthy
      db:
        condition: service_healthy
    hostname: ms_data_input

  ms_results:
    build: ./ms_results
    ports:
      - "3005:3005"
    env_file:
      - ./ms_results/.env
    depends_on:
      kafka1:
        condition: service_healthy
      db:
        condition: service_healthy
    hostname: ms_results

  ms_problem_list:
    build: ./ms_problem_list
    ports:
      - "3003:3003"
    env_file:
      - ./ms_problem_list/.env
    depends_on:
      kafka1:
        condition: service_healthy
      db:
        condition: service_healthy
    hostname: ms_problem_list
  
  ms_solver:
    build: ./ms_solver
    ports:
      - "3004:3004"
    env_file:
      - ./ms_solver/.env
    depends_on:
      kafka1:
        condition: service_healthy
      db:
        condition: service_healthy
    hostname: ms_solver

  ms_frontend:
    build: ./ms_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./ms_frontend/.env
    depends_on:
      kafka1:
        condition: service_healthy
      db:
        condition: service_healthy
